name: publish-pydoctor-apidocs
on:
- push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install package
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install .[dev]
        python -m pip install docutils pydoctor

        pydoctor --version

    - name: Generate pydoctor documentation
      run: |
        # Run pydoctor build
        tox -e docs -- $(git rev-parse HEAD)

    - name: Publish pydoctor documentation to the gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apidocs
        commit_message: "Generate pydoctor documentation"
