language: python

python:
  - "3.9-dev"
  - "3.8"
  - "3.7"
  - "3.6"

jobs:
  allow-failures:
    - python: "3.9-dev"

install:
  - pip install pipenv tox
  - pipenv install --dev

script:
  - pipenv run python -m pytest --cov Wappalyzer
  - tox -e mypy

after_success:
  - pipenv run python -m coveralls
